CREATE TABLE Categoria (
IdCategoria INT IDENTITY(1,1) NOT NULL,
Descricao VARCHAR(MAX) NOT NULL,
DataInsert DATETIME DEFAULT(GETDATE()) NULL,
Ativo BIT DEFAULT((1)) NULL,
CONSTRAINT PK_Categoria PRIMARY KEY (IdCategoria)
)
GO

